Revert "scripts: backport PKG_SOURCE_NAME"
This reverts commit 26dde6a610bde6862e09c2d97ea19797f4c79e05.

diff --git a/scripts/extract b/scripts/extract
--- a/scripts/extract
+++ b/scripts/extract
@@ -25,18 +25,21 @@ if [ -z "$3" ]; then
   exit 1
 fi
 
-[ -z "$PKG_URL" -o -z "$PKG_SOURCE_NAME" ] && exit 1
+[ -z "$PKG_URL" ] && exit 1
 [ ! -d "$SOURCES/$1" -o ! -d "$3" ] && exit 1
 
-case $PKG_SOURCE_NAME in
+for i in $PKG_URL; do
+  FILE="`basename $i`"
 
-    f="$SOURCES/$1/$PKG_SOURCE_NAME"
+  case $FILE in
+  $2)
+    f="$SOURCES/$1/$FILE"
     if [ ! -f $f ]; then
-      echo "error: File $PKG_SOURCE_NAME doesn't exists in package $1 sources directory"
+      echo "error: File $FILE doesn't exists in package $1 sources directory"
       echo "have you called scripts/extract before scripts/get ?"
       exit 1
     fi
-    case $PKG_SOURCE_NAME in
+    case $FILE in
       *.tar)
         tar xf $f -C $3
         ;;
@@ -71,3 +74,4 @@ case $PKG_SOURCE_NAME in
     esac
     ;;
   esac
+done
